baseURL = "https://colorlessean.github.io/"
languageCode = "en-us"
title = "Porch Vault"
theme = "ananke"
paginate = 2
Copyright = "© PorchVault 2020"
canonifyurls = true

[params]

# Add Buttons to the menu
# Home Page
[[menu.main]]
name = "Home"
weight = 100   #Decides the position of the button higher or lower
identifier = "home"
pre = "<br />"
url = "/"

# Contact Page
[[menu.main]]
name = "Contact"
weight = 0
identifier = "contact"
pre = "<br />"
url = "/contact"

# Blog Page
[[menu.main]]
name = "Blog"
identifier = "blog"
pre = "<br />"
url = "/post"
weight = 40

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"